language: node_js
node_js:
- '7'

cache:
  directories:
    - "${HOME}/.bower"
    - "${HOME}/.cache/bower"

install:
  - npm install
  - (cd server && exec npm install)
  - (cd client && exec npm install)

before_script:
  - npm install -g gulp-cli

script:
  - (cd server && exec npm test)
  - (cd client && exec npm test)

after_success:
  - npm run gulp

addons:
  artifacts:
    paths:
      - $(git ls-files -o test-results | tr "\n" ":")

deploy:
  provider: s3
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  bucket: $ARTIFACTS_BUCKET
  region: $ARTIFACTS_REGION
  local_dir: dist
  upload-dir: $DIST_DIR
  skip_cleanup: true
  on:
    repo: trainline/environment-manager
    all_branches: true
